Ajout d'un message visuel après le clic sur le bouton ajouter
koala819/ma-liste-de-courses pull request #1
Opened 2021-04-02 11:32 UTC by koala819

Problème : 
quand on clique que le bouton il ne se passe rien et l'utilisateur ne comprends pas pourquoi

Solution : 
=> pour prévenir l'utilisateur qu'il a cliqué sur le bouton : affichage d'un message
=> message pour informer que la fonction n'est pas encore développée.

2021-04-02 11:40 UTC, iwazaru requested changes

2021-04-02 11:40 UTC, iwazaru commented on client/index.html
> +            <input id="buttonAdd" type="submit" value="Ajouter">
"addButton" serait un meilleur nom

2021-04-02 11:40 UTC, iwazaru commented on client/index.html
>  </html>
Il manque un retour à la ligne ici

2021-04-02 11:40 UTC, iwazaru commented on client/index.js
> +const buttonAdd = document.getElementById("buttonAdd");
Changer le nom "buttonAdd" ici aussi

2021-04-02 11:40 UTC, iwazaru commented on client/index.js
> +    alert('Pas encore implémenté');
Il vaut mieux utiliser un seul type de guillemet dans le projet : " ou '

2021-04-02 11:40 UTC, iwazaru commented on client/index.js
> +})
Manque un retour à la ligne ici aussi

2021-04-04 09:10 UTC, koala819 commented on client/index.html
> +            <input id="buttonAdd" type="submit" value="Ajouter">
l'id a été changé comme conseillé

2021-04-04 09:11 UTC, koala819 commented on client/index.html
>  </html>
je ne peux pas rajouter une ligne après la balise <html>
j'utilise une extension qui indente le code et qui supprime automatiquement cette ligne
je vais regarder comment la configurer

2021-04-04 09:12 UTC, koala819 commented on client/index.js
> +const buttonAdd = document.getElementById("buttonAdd");
très pertinent, merci

2021-04-04 09:12 UTC, koala819 commented on client/index.js
> +    alert('Pas encore implémenté');
tout le code utilise le guillemet '

2021-04-04 09:13 UTC, koala819 commented on client/index.js
> +})
même remarque que pour le fichier index.html
à cause d'une extension je ne peux pas ajouter cette ligne

2021-04-04 09:16 UTC, iwazaru commented on client/index.html
>  </html>
Je crois que j'ai mis mon commentaire au mauvais endroit. Ce qui ne plait pas à git c'est l'absence d'une ligne vide à la fin, donc après `</html>`.

2021-04-04 09:20 UTC, koala819 commented on client/index.html
>  </html>
je viens de trouver où configurer ça.
c'est un paramètre de VSCode, je viens d'ajouter la ligne vide à la fin de chaque fichier

2021-04-04 14:02 UTC, iwazaru approved these changes
C'est parfait, tu peux fusionner la branche dans master !

2021-04-06 17:16 UTC, merged