Create items
koala819/ma-liste-de-courses pull request #2
Opened 2021-04-07 11:34 UTC by koala819

création de la classe Item

utilisation d'un ID pour quand l'objet est composé d'un caratère accentué et/ou un espace
 - condition ternaire défini au cas où

suppression de la liste côté HTML

création de cette liste avec un forEach en JS

2021-04-07 13:13 UTC, iwazaru commented on client/index.js
> +});
Ici, on pourrait utiliser `map` plutôt que `forEach` comme on avait fait dans le précédent projet (liste de produit). Tu saurais comment faire ?

2021-04-08 13:07 UTC, koala819 commented on client/index.js
> +});
le `forEach` a été remplacé par un `map`

2021-04-08 16:49 UTC, iwazaru requested changes

2021-04-08 16:49 UTC, iwazaru commented on client/index.js
> +    console.log(item);
Tu as oublié un `console.log` ici

2021-04-08 16:49 UTC, iwazaru commented on client/index.js
> +shoppingList.map((item) => {
Ici tu utilises `map` exactement comme un `forEach` (c'est à dire pour faire une boucle sur le tableau `shoppingList`).

Souviens-toi que l'intérêt de `map` est qu'il ne fait pas seulement une boucle, [il renvoie un nouveau tableau après avoir modifié chacun de ses éléments](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/map). Tu peux regarder comment on avait fait dans la liste de produits pour t'inspirer, sinon on regarde ça ensemble demain.

2021-04-09 10:43 UTC, iwazaru approved these changes

2021-04-09 10:43 UTC, merged